### ISSUE TITLE
Support PATCH operation on resources

### ISSUE THREAD

**Issue by miha-plesko** [xlab-si/redfish-client-python#7]
I'd propose we support following operation:

```python
system = redfish_client.connect(...).find('/redfish/v1/Systems/1')
system.patch(
  {
    "Bios": {
      "PrimaryBoot": "PXE",
      "SecondaryBoot": "CDROM"
    },
    "SKU": "abcdefg",
  }
)
```

Things to consider:
- Should client perform basic payload validation? (e.g. detect mismatch between own keys and payload keys)
- Should client parse the response? Because according to standard, response 200 doesn't always mean all the fields were updated...

@tadeboro wdyt?

/cc @aljazkosir

**Comment by tadeboro** [comment]
Just a quick link, before we reinvent the bloody thing: https://github.com/xlab-si/redfish-client-python/pull/5 This is an attempt by @matejart that tries to do roughly the same thing. Maybe we can reuse something from there.

**Comment by miha-plesko** [comment]
Ha, nice. @matejart would you mind if we extract the PATCH part of the thing from your PR? I think you're in process of review with the other parts mostly; the PATCH part is good the way you did it, so we can start using it.

**Comment by tadeboro** [comment]
>     * Should client perform basic payload validation? (e.g. detect mismatch between own keys and payload keys)

I would consider this as "nice to have" functionality since server will also perform the validation.

>     * Should client parse the response? Because according to standard, response 200 doesn't always mean all the fields were updated...

I would say this is more important to implement, since this is where validation results are reported.

**Comment by matejart** [comment]
Go ahead and use my implementation. It should be good for merge already I think ;)

> Should client perform basic payload validation? (e.g. detect mismatch between own keys and payload keys)

Nice to have, but not a priority.
I would say we offload validation to the server at this point. While we might benefit from in-client validation at the unit test stage at some point, that also means (if I understand correctly) another roundtrip to the server (ok, unless the resource payload is already cached ...). OK, come to think of it, maybe this is useful, but it's nice-to-have at this moment.

> Should client parse the response? Because according to standard, response 200 doesn't always mean all the fields were updated...

How would that work? Would it parse the returned payload as (hopefully) JSON, compare and match the obtained document with the requested payload, and raise various exceptions if things didn't match?

**Comment by matejart** [comment]
I have just realised one issue: these methods that we created modify the resource at the server, but do not update the cached representation of the resource. I suggest to at least add an invalidation of the cached resource's representation as a part of the methods.

**Comment by miha-plesko** [comment]
Good point

**Comment by tadeboro** [comment]
In https://github.com/xlab-si/redfish-client-python/commit/5faa8a867d182e5494516dd8cc42516821daecb2, @matejart implemented most of the required functionality.

What is still missing is cache invalidation, but since this is not strictly related to the issue at hand, I created a new bug report #17 that we can use to track the progress.
